token: a886a957e3d7c3cd7c0dda82fbc1653fa300cc01d32aab8c90ad41b4db8268337f2262ef6d7655917fba3
backend: backend.vk.backend

db:
  path: db.redis.db
  host: localhost
  port: 6379
  db_c: 0

dialog:
  common_answer:
    привет: Привет! Я бот-база данных! Ты можешь присылать мне текст и ключ к этому тексту. Я сохраню это у
              себя и потом по твой просьбе верну тебе текст по ключу!
    спасибо: Всегда пожалуйста!

  text_does_not_exist: Такой записи не сущетсвует
  don_t_understand: Не понимаю тебя
  action: ["сохрани", "дай"]
  ok: Хорошо
  error: Неверный запрос